# Generated by Django 5.1.1 on 2024-10-16 13:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congtybaohiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten_cong_ty', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cong_ty_bao_hiem',
            },
        ),
        migrations.CreateModel(
            name='Danhgia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loai_KH', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Danh_gia',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('ppt', models.FileField(blank=True, null=True, upload_to='ppts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vip_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('acp', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('media', models.FileField(blank=True, null=True, upload_to='news_media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taikhoan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tai_khoan', models.CharField(max_length=100, unique=True)),
                ('mat_khau', models.CharField(max_length=100)),
                ('phan_quyen', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=10)),
            ],
            options={
                'db_table': 'tai_khoan',
            },
        ),
        migrations.CreateModel(
            name='Khachhang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_va_ten', models.CharField(max_length=255)),
                ('ngay_sinh', models.DateField(default=datetime.date(2000, 1, 1))),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('dia_chi', models.CharField(max_length=255)),
                ('tham_gia_bao_hiem', models.BooleanField(default=False)),
                ('chi_tiet_bao_hiem', models.TextField()),
                ('lan_gap_1', models.TextField(blank=True, null=True)),
                ('lan_gap_2', models.TextField(blank=True, null=True)),
                ('lan_gap_3', models.TextField(blank=True, null=True)),
                ('lan_gap_4', models.TextField(blank=True, null=True)),
                ('lan_gap_5', models.TextField(blank=True, null=True)),
                ('loai_khach_hang', models.CharField(choices=[('thang', 'Thường'), ('vip', 'VIP')], max_length=10)),
                ('IS_VIP', models.BooleanField(default=False)),
                ('cong_ty_bao_hiem', models.ManyToManyField(to='Admin.congtybaohiem')),
                ('danh_gia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.danhgia')),
                ('allowed_lessons', models.ManyToManyField(blank=True, to='Admin.lesson')),
            ],
            options={
                'db_table': 'khach_hang',
            },
        ),
    ]
