# Generated by Django 5.1.1 on 2024-10-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='phan_quyen',
            field=models.CharField(choices=[('admin', 'admin'), ('manage', 'manage'), ('user', 'user')], max_length=10),
        ),
    ]
