# Generated by Django 5.1.1 on 2024-10-18 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_taikhoan_phan_quyen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='quan_ly',
            field=models.ForeignKey(blank=True, limit_choices_to={'phan_quyen': 'manage'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.taikhoan'),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='ngay_sinh',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.CreateModel(
            name='Doi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_doi', models.CharField(max_length=255)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('quan_ly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doi_quan_ly', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='khachhang',
            name='doi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khachhang_thuoc_doi', to='Admin.doi'),
        ),
    ]
