# Generated by Django 5.1.1 on 2024-10-18 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_khachhang_quan_ly_alter_khachhang_ngay_sinh_doi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doi',
            name='quan_ly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doi_quan_ly', to='Admin.taikhoan'),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='doi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khachhang_thuoc_doi', to='Admin.doi'),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='quan_ly',
            field=models.ForeignKey(blank=True, limit_choices_to={'phan_quyen': 'manage'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khachhang_quan_ly', to='Admin.taikhoan'),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='so_dien_thoai',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
