# Generated by Django 5.1.1 on 2024-10-20 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_taikhoan_khachhang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='IS_VIP',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='lan_gap_1',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='lan_gap_2',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='lan_gap_3',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='lan_gap_4',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='lan_gap_5',
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='loai_khach_hang',
            field=models.CharField(choices=[('thang', 'Thường'), ('vip', 'VIP')], default='thang', max_length=10),
        ),
        migrations.CreateModel(
            name='LanGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('ngay_gap', models.DateField()),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lan_gaps', to='Admin.khachhang')),
            ],
        ),
    ]
