# Generated by Django 5.1.1 on 2024-10-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_remove_khachhang_is_vip_remove_khachhang_lan_gap_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='loai_khach_hang',
        ),
        migrations.AddField(
            model_name='khachhang',
            name='IS_VIP',
            field=models.BooleanField(default=False),
        ),
    ]
