# Generated by Django 5.1.1 on 2024-10-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_remove_khachhang_loai_khach_hang_khachhang_is_vip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='langap',
            name='ngay_gap',
        ),
    ]
