# Generated by Django 5.1.1 on 2024-10-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_lesson_kn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='slides/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='slides/videos/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='slides/audios/')),
                ('options', models.JSONField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
