# Generated by Django 5.1.1 on 2024-10-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_slide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={},
        ),
        migrations.RemoveField(
            model_name='slide',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='options',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='order',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='results',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='video',
        ),
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.JSONField(),
        ),
    ]
