# Generated by Django 5.1.1 on 2024-10-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_alter_slide_options_remove_slide_audio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='title',
            new_name='file_url',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='content',
        ),
        migrations.AddField(
            model_name='slide',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
