# Generated by Django 5.1.1 on 2024-10-24 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_rename_title_slide_file_url_remove_slide_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='activation_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
